[package]
name = "squish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
arboard = "3.4.1"
bytes = "1.10.0"
clap = { version = "4.5.29", features = ["derive"] }
colored = "3.0.0"
image = "0.25.3"
infer = "0.19.0"
tempfile = "3.19.1"

[dev-dependencies]
assert_cmd = "2.0.16"
