[package]
name = "squish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
arboard = "3.5.0"
bytes = "1.10.1"
clap = { version = "4.5.35", features = ["derive"] }
colored = "3.0.0"
image = "0.25.6"
infer = "0.19.0"
tempfile = "3.19.1"

[dev-dependencies]
assert_cmd = "2.0.17"
