[advisories]
ignore = [
    "RUSTSEC-2024-0436",
]

[licenses]
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "MIT",
    "MPL-2.0",
    "NCSA",
    "Unicode-3.0",
    "Zlib",
]
