name: main

on:
  push:
    branches:
      - main

env:
  CARGO_PROFILE_DEV_DEBUG: "0"
  CARGO_TERM_COLOR: always

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
      workflows: ${{ steps.filter.outputs.workflows }}
      yml: ${{ steps.filter.outputs.yml }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            code:
              - "src/**"
              - "tests/**"
              - "**/*.rs"
              - Cargo.*
              - clippy.toml
              - dist-workspace.toml
              - rust-toolchain.toml
              - mise.toml
              - mise.lock
              - ".github/workflows/main.yml"
            workflows:
              - ".github/**/*.yml"
              - "mise.toml"
              - "mise.lock"
            yml:
              - "**.yml"
              - "**.yaml"
              - "mise.toml"
              - "mise.lock"

  build:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up mise
        uses: jdx/mise-action@v5
        with:
          install_args: rust
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Check formatting
        run: mise run fmt:check
      - name: Lint
        run: mise run lint
      - name: Build
        run: mise run build
      - name: Test
        env:
          RUST_BACKTRACE: 0
        run: mise run test

  lint-yaml:
    needs: changes
    if: ${{ needs.changes.outputs.yml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up mise
        uses: jdx/mise-action@v5
        with:
          install_args: yamlfmt
      - name: Lint YAML
        run: mise run lint:yaml

  lint-workflows:
    needs: changes
    if: ${{ needs.changes.outputs.workflows == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up mise
        uses: jdx/mise-action@v5
        with:
          install_args: actionlint
      - name: Lint workflows
        run: mise run lint:actions
